Repository woowa-techcamp-2021/deal-5, pull requests merged in 2021-07, with the labels that each got.

#1 feat: 초기 세팅
  .eslintrc
  .prettierrc
  babel.config.json
  package-lock.json
  package.json
  src/app.ts
  src/pages/chattings.html
  src/pages/locationedit.html
  src/pages/main.html
  src/pages/newpost.html
  src/pages/saleproductdetail.html
  src/pages/submain.html
  src/routers/index.ts
  tsconfig.json
  webpack.config.js
Labels: enhancement

#30 Location 페이지 마크업 완료
  client/src/assets/svgIcons.ts
  client/src/components/Location/Location.ts
  client/src/components/Location/LocationButton.ts
  client/src/components/Location/LocationList.ts
  client/src/components/Location/index.ts
  client/src/components/Register/Register.ts
  client/src/components/Share/InputPopup.ts
  client/src/index.ts
  client/src/scss/index.scss
  client/src/scss/location.scss
  client/src/scss/root.scss
Labels: enhancement

#36 feat: chatDetail 마크업 완료
  client/src/components/ChatDetail/ChatBar.ts
  client/src/components/ChatDetail/ChatBubble.ts
  client/src/components/ChatDetail/ChatDetail.ts
  client/src/components/ChatDetail/Chatting.ts
  client/src/components/ChatDetail/InfoProduct.ts
  client/src/components/ChatDetail/index.ts
  client/src/index.ts
  client/src/scss/chatDetail.scss
  client/src/scss/index.scss
  client/src/scss/root.scss
Labels: enhancement

#44 Feature/#43 chat detail
  client/src/assets/utils/historyBack.js
  client/src/components/ChatDetail/ChatBar.ts
  client/src/components/ChatDetail/ChatDetail.ts
  client/src/components/ChatDetail/ChatSendButton.ts
  client/src/components/Share/Alert.ts
  client/src/components/Share/CommonHeader.ts
  client/src/components/Share/InputPopup.ts
  client/src/scss/chatDetail.scss
  client/src/scss/root.scss
Labels: 기능

#46 feat : 상품상세페이지 마크업
  README.md
  client/src/assets/imgs/item2.jpeg
  client/src/assets/imgs/item3.png
  client/src/components/ItemDetail/ItemDetail.ts
  client/src/components/ItemDetail/ItemDetailBody.ts
  client/src/components/ItemDetail/ItemDetailFooter.ts
  client/src/components/ItemDetail/Slider.ts
  client/src/components/ItemDetail/index.ts
  client/src/components/Share/Button.ts
  client/src/components/Share/DropDown.ts
  client/src/index.ts
  client/src/scss/index.scss
  client/src/scss/itemDetail.scss
  client/src/scss/root.scss
Labels: FE

#47 feat: newPost 페이지 마크업 완료
  client/src/assets/imgs/item2.jpeg
  client/src/assets/imgs/item3.png
  client/src/assets/svgIcons.ts
  client/src/components/NewPost/ImageButton.ts
  client/src/components/NewPost/ImagesHolder.ts
  client/src/components/NewPost/ItemPrice.ts
  client/src/components/NewPost/NewPost.ts
  client/src/components/NewPost/PostContent.ts
  client/src/components/NewPost/PostTitle.ts
  client/src/components/NewPost/SaleLocation.ts
  client/src/components/NewPost/index.ts
  client/src/index.ts
  client/src/scss/chatDetail.scss
  client/src/scss/index.scss
  client/src/scss/newPost.scss
  client/src/scss/root.scss
Labels: FE, 기능

#55 Feature/#48 newpost
  .gitignore
  client/src/assets/imgs/.DS_Store
  client/src/assets/utils/addPriceComma.ts
  client/src/assets/utils/autoHeightTextarea.ts
  client/src/assets/utils/historyBack.ts
  client/src/components/ChatDetail/ChatBar.ts
  client/src/components/NewPost/ImageButton.ts
  client/src/components/NewPost/ImagesHolder.ts
  client/src/components/NewPost/ItemCategory.ts
  client/src/components/NewPost/ItemPrice.ts
  client/src/components/NewPost/NewPost.ts
  client/src/components/NewPost/PostContent.ts
  client/src/components/NewPost/PostTitle.ts
  client/src/scss/newPost.scss
  client/src/scss/root.scss
Labels: FE, 기능

#72 Feature/#71 jwt auth
  client/src/apis/user.ts
  client/src/assets/utils/parseJWT.ts
  client/src/components/SignIn/SignIn.ts
  server/action/auth.ts
  server/action/user.ts
Labels: BE, 기능

#76 repactor : main 페이지
  client/src/apis/main.ts
  client/src/assets/utils/fetchTemplets.ts
  client/src/components/main/BookmarkList.ts
  client/src/components/main/CategoryBody.ts
  client/src/components/main/Item.ts
  client/src/components/main/MainHeader.ts
  client/src/components/main/Mainbody.ts
  client/src/components/main/Menu.ts
  client/src/components/main/SalesList.ts
  client/src/scss/main.scss
  client/src/scss/root.scss
  server/action/main.ts
  server/query/main.ts
  server/routers/main.ts
Labels: BE, 기능

#77 Feature/#75 refresh token
  client/src/apis/user.ts
  client/src/components/LogIn/LogIn.ts
  client/src/components/LogIn/index.ts
  client/src/components/MyAccount/MyAccount.ts
  client/src/components/MyAccount/index.ts
  client/src/components/Register/Register.ts
  client/src/components/SignIn/index.ts
  client/src/index.ts
  server/action/main.ts
  server/action/refresh.ts
  server/action/user.ts
  server/app.ts
  server/package-lock.json
  server/package.json
  server/query/auth.ts
  server/query/user.ts
  server/routers/middlewares.ts
  server/utils/jwtAuth.ts
Labels: BE, 기능

#79 style: 변수 이름 불일치 수정
  server/action/refresh.ts
  server/action/user.ts
  server/routers/middlewares.ts
  server/utils/jwtAuth.ts
Labels: 버그

#81 Feature/#80 myaccount
  client/src/apis/user.ts
  client/src/components/MyAccount/MyAccount.ts
  client/src/components/main/MainHeader.ts
  client/src/index.ts
  server/action/user.ts
  server/routers/middlewares.ts
  server/routers/user.ts
Labels: BE, FE, 기능

#89 Feature/#85 location api
  client/src/apis/user.ts
  client/src/components/Location/Location.ts
  client/src/components/Register/Register.ts
  client/src/components/main/Main.ts
  server/action/user.ts
  server/package-lock.json
  server/package.json
  server/query/user.ts
  server/routers/user.ts
Labels: BE, 기능

#94 Feature/#92 newpost api
  .gitignore
  client/src/apis/newpost.ts
  client/src/assets/utils/fetchTemplets.ts
  client/src/components/ItemDetail/Slider.ts
  client/src/components/NewPost/ImageButton.ts
  client/src/components/NewPost/ImagesHolder.ts
  client/src/components/NewPost/ItemPrice.ts
  client/src/components/NewPost/NewPost.ts
  client/src/components/NewPost/PostContent.ts
  client/src/components/NewPost/PostTitle.ts
  client/src/components/NewPost/SaleLocation.ts
  client/src/components/main/BookmarkList.ts
  client/src/components/main/Item.ts
  client/src/components/main/Main.ts
  client/src/components/main/Mainbody.ts
  client/src/components/main/SalesList.ts
  client/src/scss/main.scss
  server/app.ts
  server/package-lock.json
  server/package.json
  server/query/newpost.ts
  server/routers/index.ts
  server/routers/newpost.ts
  server/routers/user.ts
Labels: BE, 기능

#95 Feature/#92 newpost api
  client/src/apis/newpost.ts
  client/src/assets/utils/fetchTemplets.ts
  client/src/components/ItemDetail/ItemDetail.ts
  client/src/components/ItemDetail/Slider.ts
  client/src/components/NewPost/NewPost.ts
  client/src/components/main/BookmarkList.ts
  client/src/components/main/Item.ts
  client/src/components/main/Mainbody.ts
  client/src/components/main/SalesList.ts
  server/action/newpost.ts
  server/query/newpost.ts
  server/routers/newpost.ts
  server/routers/user.ts
Labels: BE, FE, 기능
